#!/bin/bash
set -euf -o pipefail
exec 1> >(logger -s -t $(basename $0)) 2>&1 
cat>>/etc/sudoers.d/95-ansible-pipelining<<EOF
#
# Enable pipelining mode and sudo availability for Ansible
#
Defaults:k5user    !requiretty
Defaults:ubuntu    !requiretty
EOF
chmod 640 /etc/sudoers.d/95-ansible-pipelining
echo "Userdata done"
